CREATE USER "INFORMATICO_SISTEMAS" IDENTIFIED BY "Paralelepipedo1234";
GRANT CREATE SESSION TO "INFORMATICO_SISTEMAS";
GRANT CREATE TABLE TO "INFORMATICO_SISTEMAS";
GRANT SELECT ANY TABLE TO "INFORMATICO_SISTEMAS";
GRANT INSERT ANY TABLE TO "INFORMATICO_SISTEMAS";
GRANT UPDATE ANY TABLE TO "INFORMATICO_SISTEMAS";
GRANT DELETE ANY TABLE TO "INFORMATICO_SISTEMAS";
ALTER USER INFORMATICO_SISTEMAS QUOTA UNLIMITED ON DATA;
